---
title: "Kakao_Pay Data-scientist 사전과제 1번"
author: "Dae woong Yeo"
---

```{r}

#Data Loading 

setwd("C:/data")
dutchpay_claim <- read.csv("dutchpay_claim.csv", head=TRUE, encoding="utf-8")
dutchpay_claim_detail <- read.csv("dutchpay_claim_detail.csv", head=TRUE, encoding="utf-8")

#preserve raw file.
dutchpay_claim_ <- dutchpay_claim
dutchpay_claim_detail_ <- dutchpay_claim_detail

#Modify the variable type 
dutchpay_claim_$claim_id <- as.character(dutchpay_claim_$claim_id)
dutchpay_claim_$claim_at <- as.POSIXct(dutchpay_claim_$claim_at)
dutchpay_claim_$claim_user_id <- as.character(dutchpay_claim_$claim_user_id)

#Modify the variable type 
dutchpay_claim_detail_$claim_detail_id <-as.character(dutchpay_claim_detail_$claim_detail_id)
dutchpay_claim_detail_$claim_id <-as.character(dutchpay_claim_detail_$claim_id)
dutchpay_claim_detail_$recv_user_id <-as.character(dutchpay_claim_detail_$recv_user_id)
dutchpay_claim_detail_$status <-as.character(dutchpay_claim_detail_$status)

#check the variable type of dutchpay_claim table
cat("claim_id : " , mode(dutchpay_claim_$claim_id), "\n")
cat("claim_at : " , mode(dutchpay_claim_$claim_at), "\n")
cat("claim_user_id : " , mode(dutchpay_claim_$claim_user_id), "\n")

#check the variable type of dutchpay_claim_detail table
cat("claim_detail_id : " , mode(dutchpay_claim_detail_$claim_detail_id), "\n")
cat("claim_id : " , mode(dutchpay_claim_detail_$claim_id), "\n")
cat("recv_user_id : " , mode(dutchpay_claim_detail_$recv_user_id), "\n")
cat("claim_amount : " , mode(dutchpay_claim_detail_$claim_amount), "\n")
cat("send_amount : " , mode(dutchpay_claim_detail_$send_amount), "\n")
cat("status : " , mode(dutchpay_claim_detail_$status), "\n")

#check the data 
head(dutchpay_claim_,3)
tail(dutchpay_claim_,3)
print("####################")
head(dutchpay_claim_detail_,3)
tail(dutchpay_claim_detail_,3)
```

#

```{r}
library(dplyr)
options(dplyr.summarise.inform = FALSE)
 #유저별 더치페이 요청횟수
claim_num_by_user<- dutchpay_claim_ %>% group_by(claim_user_id) %>% summarize(dutchpay_request_num = n()) 
head(claim_num_by_user)
colnames(claim_num_by_user) <- c("user_id", "dutchpay_request_num")

 #유저별 더치페이 요청 받은 총 건수 
request_recv_num_by_user<- dutchpay_claim_detail_ %>% group_by(recv_user_id) %>% summarize(request_recv_num = n()) 
head(request_recv_num_by_user)

# 유저별 더치페이 요청 받은 건에 대한 응답건수(SEND, CHECK)
response_rate_user_check <- dutchpay_claim_detail_[dutchpay_claim_detail_$status=="CHECK",] %>% group_by(recv_user_id) %>% summarize(response_check = n()) 
response_rate_user_send <- dutchpay_claim_detail_[dutchpay_claim_detail_$status=="SEND",] %>% group_by(recv_user_id) %>% summarize(response_send = n()) 
response_rate_user_checksend <- dutchpay_claim_detail_[dutchpay_claim_detail_$status!="CLAIM",] %>% group_by(recv_user_id) %>% summarize(response_checksend = n())
response_rate_user_claim <- dutchpay_claim_detail_[dutchpay_claim_detail_$status=="CLAIM",] %>% group_by(recv_user_id) %>% summarize(response_claim = n())

head(response_rate_user_send) 
head(response_rate_user_check)
head(response_rate_user_checksend)
head(response_rate_user_claim)

#response rate of each users 
recv_user_response <- merge(request_recv_num_by_user, response_rate_user_checksend, by="recv_user_id" ,all.x = T)
recv_user_response[is.na(recv_user_response$response_checksend)==T,]$response_checksend <- 0
recv_user_response$recv_user_response_rate <- recv_user_response$response_checksend / recv_user_response$request_recv_num
head(recv_user_response)
colnames(recv_user_response) <- c("user_id", "request_recv_num", "response_checksend", "recv_user_response_rate")

#response rate - claim request
recv_user_response_claim <- merge(recv_user_response, claim_num_by_user, by="user_id", all.x = T)
request_assign <- rep(NA,length(recv_user_response_claim$dutchpay_request_num))
recv_user_response_claim <- data.frame(cbind(recv_user_response_claim,request_assign))
head(recv_user_response_claim)
recv_user_response_claim[is.na(recv_user_response_claim$dutchpay_request_num)==T,]$request_assign <-0 #더치페이 요청안했으면 0
recv_user_response_claim[is.na(recv_user_response_claim$dutchpay_request_num)==F,]$request_assign <-1 #더치페이 요청했으면 1
recv_user_response_claim[is.na(recv_user_response_claim$dutchpay_request_num)==T,]$dutchpay_request_num <- 0

#recv_user_response_claim
#recv_user_response_claim <- recv_user_response_claim[!is.na(recv_user_response_claim$dutchpay_request_num)==T,]
recv_user_response_claim$request_assign<-as.factor(recv_user_response_claim$request_assign)


## 다음 더치페이 요청까지 걸린 시간(하루단위)
library(reshape2)
cluid <- melt(data = dutchpay_claim_, 
                          id.vars = c("claim_user_id"), 
                            measure.vars = c("claim_at"))
maxclu <- dcast(data = cluid, claim_user_id ~ variable, fun = max)
#maxclu
minclu <- dcast(data = cluid, claim_user_id ~ variable, fun = min)
#minclu

clus <- merge(minclu, maxclu, by="claim_user_id", all.x = T)
#clus
def <- rep(0, nrow(clus))
clus_n <- data.frame(cbind(clus,def))
clus_n$def <- clus_n$claim_at.y - clus_n$claim_at.x
head(clus_n)
#dutchpay_claim_[dutchpay_claim_$claim_user_id=="003a6a2e138d9c7",]
#as.POSIXct(1578285227, origin = '1970-01-01',tz='UTC')
#as.POSIXct(1581859830, origin = '1970-01-01',tz='UTC')
#as.POSIXct(3574603, origin = '1970-01-01',tz='UTC')

colnames(clus_n) <- c("user_id", "begin", "last", "stayday")

recv_user_response_claim <- merge(recv_user_response_claim, clus_n, by="user_id", all.x = T)
recv_user_response_claim$stayday <- recv_user_response_claim$stayday/86400 #1day= 86400 in num
head(recv_user_response_claim)

recv_user_response_claim$begin[is.na(recv_user_response_claim$begin)==T] <-0 
recv_user_response_claim$last[is.na(recv_user_response_claim$last)==T] <-0 
recv_user_response_claim$stayday[is.na(recv_user_response_claim$stayday)==T] <-0 

head(recv_user_response_claim)

def2 <- rep(0, nrow(recv_user_response_claim))
def2_ <- data.frame(cbind(recv_user_response_claim,def2))

fiv <- def2_$dutchpay_request_num / def2_$stayday  
fiv[is.nan(fiv)==T | is.infinite(fiv)==T ] = 0 
def2_$def2 <- fiv
head(def2_)
recv_user_response_claim <- def2_
#recv_user_response_claim$begin <- as.POSIXct(recv_user_response_claim$begin, origin = '1970-01-01',tz='UTC')
#recv_user_response_claim$last <- as.POSIXct(recv_user_response_claim$last, origin = '1970-01-01',tz='UTC')
head(recv_user_response_claim)

data_1 <- data.frame(recv_user_response_claim$user_id,
                         recv_user_response_claim$request_recv_num, 
                         recv_user_response_claim$response_checksend, 
                         recv_user_response_claim$recv_user_response_rate, 
                         recv_user_response_claim$dutchpay_request_num, 
                         recv_user_response_claim$stayday,
                         recv_user_response_claim$def2)
colnames(data_1) <- c("user_id","res_req_num", "res_num", "res_rate", "dp_req_num", "use_day", "dp_req_rate")

options(digits=2)
head(data_1)
```


```{r}
#plot(final_data$res_rate, final_data$dp_req_rate)
#final_data[final_data$dp_req_rate == max(final_data$dp_req_rate),]
#library(openxlsx)
#write.xlsx(final_data$dp_req_rate,"dp_req_rate.xlsx")
library(ggplot2)
#응답률 0과 1의 분포
ggplot(data_1, aes(x=res_rate)) + geom_histogram(bins=50)
#더치페이 요청횟수 분포
ggplot(data_1, aes(x=dp_req_num)) + geom_histogram(bins=50)
# 응답률 구간 binning 처리 및 범주화
library(rbin)
data_1_ <- data_1
data_bins <- rbin_manual(data_1, dp_req_num, res_rate, c(0.2,0.4,0.6,0.8))
data_bins_ <- rbin_create(data_1_, res_rate, data_bins)
head(data_bins_)

data_2 <- data_bins_[-c(2,3,6,7)]
head(data_2)

data_2_res<- data_2[data_2$res_rate != 1,]
head(data_2_res)

names(data_2_res)
colnames(data_2_res) <- c("user_id", "res_rate","dp_req_num",
                          "0.0<res_rate<0.2" , "0.2<=res_rate<0.4" , 
                          "0.4<=res_rate<0.6","0.6<=res_rate<0.8",
                          "0.8<=res_rate<1.0")
data_2_res <- data_2_res[-c(1,2)]

res_category <- cbind(data_2_res[1], res_factor = factor(names(data_2_res)[1 + max.col(data_2_res[-1])], ordered = TRUE))
head(res_category)
'
data_2_res5<- data_2[data_2$res_rate >=0.8 & data_2$res_rate < 1,]
data_2_res5
data_2_res4<- data_2[data_2$res_rate >=0.6 & data_2$res_rate < 0.8,]
data_2_res4
data_2_res3<- data_2[data_2$res_rate >=0.4 & data_2$res_rate < 0.6,]
data_2_res3
data_2_res2<- data_2[data_2$res_rate >=0.2 & data_2$res_rate < 0.4,]
data_2_res2
data_2_res1<- data_2[data_2$res_rate >=0 & data_2$res_rate < 0.2,]
boxplot(data_2_res5$dp_req_num)
summary(data_2_res4$dp_req_num)
summary(data_2_res3$dp_req_num)
summary(data_2_res2$dp_req_num)
summary(data_2_res1$dp_req_num)
ggplot(data_2_resone, aes(x=dp_req_num)) + geom_histogram(bins=1000)
ggplot(data_2_reszero, aes(x=dp_req_num)) + geom_histogram(bins=1000)
ggplot(data_2_res4, aes(x=dp_req_num)) + geom_histogram(bins=1000)
'

# Kruskal walis 검정 

library(FSA)
kruskal.test(dp_req_num~res_factor, data=res_category)
res_dt = dunnTest(dp_req_num~res_factor, data=res_category ,method="bh")
res_dt

# Visualize
comparisons <- list( c("0.0<res_rate<0.2", "0.2<=res_rate<0.4"), 
                     c("0.2<=res_rate<0.4", "0.4<=res_rate<0.6") ,
                     c("0.4<=res_rate<0.6", "0.6<=res_rate<0.8"),
                     c("0.6<=res_rate<0.8", "0.8<=res_rate<1.0"))
library(ggpubr)
ggboxplot(res_category, x = "res_factor", y = "dp_req_num",
          color = "res_factor", palette = "jco") + 
  geom_hline(yintercept = median(res_category$dp_req_num), linetype = 2)+
  stat_compare_means(comparisons = comparisons) +
  stat_compare_means(label.y = 200) 


```

```{r}

# #데이터 탐색 
# 
# plot(sort(table(recv_user_response_claim$request_recv_num)), xlab="더치페이 요청 받은 건수의 분포", ylab="빈도수")
# plot(sort(table(recv_user_response_claim$response_checksend)), xlab="더치페이 요청에 대한 응답 건수의 분포", ylab="빈도수")
# plot(sort(table(recv_user_response_claim$recv_user_response_rate)), xlab="더치페이 요청에 대한 응답률의 분포", ylab="빈도수")
# plot(sort(table(recv_user_response_claim$dutchpay_request_num)), xlab="더치페이 요청 건수의 분포", ylab="빈도수")
# 
# #각 응답횟수 수준에서 더치페이 요청횟수 분포
# hist(recv_user_response_claim$recv_user_response_rat[recv_user_response_claim$dutchpay_request_num==0])
# hist(recv_user_response_claim$recv_user_response_rat[recv_user_response_claim$dutchpay_request_num==1])
# hist(recv_user_response_claim$recv_user_response_rat[recv_user_response_claim$dutchpay_request_num==2])
# hist(recv_user_response_claim$recv_user_response_rat[recv_user_response_claim$dutchpay_request_num==3])
# hist(recv_user_response_claim$recv_user_response_rat[recv_user_response_claim$dutchpay_request_num==4])
# hist(recv_user_response_claim$recv_user_response_rat[recv_user_response_claim$dutchpay_request_num==5])
# hist(recv_user_response_claim$recv_user_response_rat[recv_user_response_claim$dutchpay_request_num==6])
# hist(recv_user_response_claim$recv_user_response_rat[recv_user_response_claim$dutchpay_request_num==7])
# 
# latent_model2 <- recv_user_response_claim[recv_user_response_claim$recv_user_response_rate  > 0.125  & recv_user_response_claim$recv_user_response_rate < 0.9863014,]
# 
# for(i in sort(unique(recv_user_response_claim$recv_user_response_rate))){
# hist(recv_user_response_claim$dutchpay_request_num[recv_user_response_claim$recv_user_response_rate==i],xlab=i)
# }
# 
# hist(recv_user_response_claim$recv_user_response_rate[recv_user_response_claim$dutchpay_request_num==48])
#      
#      
# boxplot(recv_user_response_claim$dutchpay_request_num[recv_user_response_claim$recv_user_response_rate==0])
# boxplot(recv_user_response_claim$dutchpay_request_num[recv_user_response_claim$recv_user_response_rate==0],outline=FALSE)$out
# boxplot(recv_user_response_claim$dutchpay_request_num[recv_user_response_claim$recv_user_response_rate==0.75],outline=FALSE)$out
# recv_user_response_claim$recv_user_response_rate[3]
# quantile(recv_user_response_claim$dutchpay_request_num,na.rm=T,probs=seq(0,1,0.01))
# #quantile(recv_user_response_claim$dutchpay_request_num[recv_user_response_claim$dutchpay_request_num > 1 & recv_user_response_claim$dutchpay_request_num < 15],na.rm=T)
# 
# boxplot(recv_user_response_claim$dutchpay_request_num[recv_user_response_claim$dutchpay_request_num > 0])$stats
# boxplot(recv_user_response_claim$recv_user_response_rate[recv_user_response_claim$recv_user_response_rate > 0 & recv_user_response_claim$recv_user_response_rate < 1])$stats
# 
# boxplot(recv_user_response_claim$recv_user_response_rate[recv_user_response_claim$recv_user_response_rate > 0.125 & recv_user_response_claim$recv_user_response_rate < 0.9863014])
# boxplot(recv_user_response_claim$dutchpay_request_num[recv_user_response_claim$dutchpay_request_num > 0 & recv_user_response_claim$dutchpay_request_num < 9])$stat
# 
# raw_model <- recv_user_response_claim
# latent_model <- recv_user_response_claim[recv_user_response_claim$recv_user_response_rate  > 0.125  & recv_user_response_claim$recv_user_response_rate < 0.9863014 &
#                                          recv_user_response_claim$dutchpay_request_num > 0,] 
# plot(raw_model$recv_user_response_rate, raw_model$dutchpay_request_num,type="p", cex=0.5)
# plot(latent_model$recv_user_response_rate, latent_model$dutchpay_request_num,type="p", cex=0.5)
# hist(latent_model$recv_user_response_rate)
# hist(latent_model$dutchpay_request_num)
# table(latent_model$dutchpay_request_num)
# latent_model <- recv_user_response_claim[recv_user_response_claim$recv_user_response_rate  > 0.125  & recv_user_response_claim$recv_user_response_rate < 1,]
# latent_model
# 
# #반응변수 y= 더치페이 요청 건수는 zero - inflated이고 overdispersion한 특성이 있음
# #단위시간당을 정의할수가 없어서 사용불가능. 그래도 일단 try 
# 
# #poisson regression 모형
# library(MASS)
# pois.fit<- glm(dutchpay_request_num~response_checksend, data=recv_user_response_claim,family=poisson)
# summary(pois.fit)
# 
# 
# #overdispersion 확인 
# #1) VMR 
# var(recv_user_response_claim$dutchpay_request_num)/mean(recv_user_response_claim$dutchpay_request_num)
# #2) Test
# require(qcc)
# qcc.overdispersion.test(recv_user_response_claim$dutchpay_request_num, type="poisson")
# 
# #quasi-posisson
# require(qcc)
# qcc.overdispersion.test(recv_user_response_claim_$dutchpay_request_num, type="poisson")
# pchisq(202606-202534, df=1, lower.tail = FALSE)
# deviance(pois.fit)/df.residual(pois.fit)
# exp(coef(pois.fit))
# plot(recv_user_response_claim_$recv_user_response_rate, recv_user_response_claim_$dutchpay_request_num)
# 
# #Negative binomial regression 모형
# library(MASS)
# nb.fit<- glm.nb(dutchpay_request_num~recv_user_response_rate, data=recv_user_response_claim,maxit=100)
# pred  <- predict(nb.fit, recv_user_response_claim)
# plot(recv_user_response_claim$recv_user_response_rate,recv_user_response_claim$dutchpay_request_num)
# lines(recv_user_response_claim$recv_user_response_rate, pred, lwd=1, col = "red")
# summary(nb.fit)
# 
# #zero-flated 확인
# table(recv_user_response_claim$dutchpay_request_num)
# plot(sort(table(recv_user_response_claim$dutchpay_request_num)), xlab="distribution of dutchpay request", ylab="Freq")
# 
# #hurdle poisson(truncated pois)
# library(pscl)
# hpois.fit <- hurdle(dutchpay_request_num~response_checksend, data =recv_user_response_claim, link="logit", dist="poisson")
# summary(hpois.fit)
# 
# #hurdle nb(truncated nb)
# library(pscl)
# hnb.fit <- hurdle(dutchpay_request_num~response_checksend, data =recv_user_response_claim, link="logit", dist="negbin")
# summary(hnb.fit)
# 
# library(pscl)
# zpois.fit <- zeroinfl(dutchpay_request_num~response_checksend, data =recv_user_response_claim, link="logit", dist = "poisson")
# summary(zpois.fit)
# 
# #Zero-inflated Negative binomial regression 모형 
# library(pscl)
# zinb.fit <- zeroinfl(dutchpay_request_num~recv_user_response_rate, data =recv_user_response_claim, link="logit", dist = "negbin")
# summary(zinb.fit)
# pred  <- predict(zinb.fit, recv_user_response_claim)
# plot(recv_user_response_claim$dutchpay_request_num,pred)
# plot(recv_user_response_claim$recv_user_response_rate,recv_user_response_claim$dutchpay_request_num)
# lines(recv_user_response_claim$recv_user_response_rate, pred, lwd=1, col = "red")
# 
# # 효과확인
# expCoef <- exp(coef((zinb.fit)))
# expCoef <- matrix(expCoef, ncol = 2)
# rownames(expCoef) <- c('Intercept', 'checksend')
# colnames(expCoef) <- c("Count_model","Zero_inflation_model")
# expCoef
# 
# latent_model <- recv_user_response_claim[recv_user_response_claim$recv_user_response_rate  > 0.125  & recv_user_response_claim$recv_user_response_rate < 0.9863014,]
# plot(latent_model$recv_user_response_rate, latent_model$dutchpay_request_num)
# lm.fit <- lm(dutchpay_request_num~recv_user_response_rate, data =latent_model)
# summary(lm.fit)
# plot(lm.fit)
# pred  <- predict(lm.fit, recv_user_response_claim)
# plot(recv_user_response_claim$recv_user_response_rate,recv_user_response_claim$dutchpay_request_num)
# lines(recv_user_response_claim$recv_user_response_rate, pred, lwd=1, col = "red")
# summary(lm.fit)
# plot(lm.fit)
# plot(recv_user_response_claim$response_checksend,recv_user_response_claim$dutchpay_request_num)
# abline(zinb.fit,col="red")
# abline(pois.fit,col="yellow")
# abline(nb.fit,col="cyan")
# abline(zpois.fit,col="blue")
# abline(hpois.fit,col="green")
# abline(hnb.fit,col="brown")
# abline(lm.fit,col="orange")
# 
# library(quantreg)
# 
# #linear regression
# plot(raw_model$recv_user_response_rate, raw_model$dutchpay_request_num,type="p", cex=0.5)
# plot(latent_model$recv_user_response_rate, latent_model$dutchpay_request_num,type="p", cex=0.5)
# abline(lm(dutchpay_request_num~recv_user_response_rate, data=latent_model),col="red")
# lmfit <- lm(dutchpay_request_num~recv_user_response_rate+request_assign, data=raw_model)
# summary(lmfit)
# 
# #Nonparametric Quantile regression - 같은 x값에 여러개의 y값이 존재.. 각 y값의 분위에 따른 수준에서 회귀모형적합 
# library(quantreg.nonpar)
# basis.bsp <- create.bspline.basis(breaks = quantile(latent_model$recv_user_response_rate, c(0:10)/10))
# B <- 500
# B.boot <- 100
# taus <- c(1:24)/25
# print.taus <- c(1:4)/5
# alpha <- 0.05
# piv.bsp <- npqr(formula = dutchpay_request_num ~ recv_user_response_rate, data=latent_model, basis = basis.bsp)
# 
# #Localized nonparametic regression (Loess)
# ggplot(latent_model, aes(x=recv_user_response_rate, y=dutchpay_request_num)) + geom_point() + stat_smooth(method='loess')
# #0.5미만에서 변동없다가 0.5이상부터 급증추세 보여줌
# 
# qs <- 1:9/10
# qrfit <- rq(dutchpay_request_num~recv_user_response_rate, tau=qs, data=latent_model)
# plot(summary(qrfit,se="boot"), parm="recv_user_response_rate")
# summary(qrfit,se="boot")
# 
# #Quatile regression
# summary(rq(dutchpay_request_num~recv_user_response_rate, tau=0.1, data=latent_model),se="boot")
# #summary(rq(dutchpay_request_num~recv_user_response_rate, tau=0.2, data=latent_model),se="boot")
# summary(rq(dutchpay_request_num~recv_user_response_rate, tau=0.3, data=latent_model),se="boot")
# #summary(rq(dutchpay_request_num~recv_user_response_rate, tau=0.4, data=latent_model),se="boot")
# summary(rq(dutchpay_request_num~recv_user_response_rate, tau=0.5, data=latent_model),se="boot")
# #summary(rq(dutchpay_request_num~recv_user_response_rate, tau=0.6, data=latent_model),se="boot")
# summary(rq(dutchpay_request_num~recv_user_response_rate, tau=0.7, data=latent_model),se="boot")
# #summary(rq(dutchpay_request_num~recv_user_response_rate, tau=0.8, data=latent_model),se="boot")
# summary(rq(dutchpay_request_num~recv_user_response_rate, tau=0.9, data=latent_model),se="boot")
# 
# ggplot(latent_model, aes(x=recv_user_response_rate, y=dutchpay_request_num)) + 
#   geom_point() + geom_quantile(quantiles = c(0.9,0.7,0.5,0.3,0.1))
# 
# plot(latent_model$recv_user_response_rate, latent_model$dutchpay_request_num,type="p", cex=0.5)
# abline(rq(dutchpay_request_num~recv_user_response_rate, tau=0.1, data=latent_model), col="red")
# #abline(rq(dutchpay_request_num~recv_user_response_rate, tau=0.2, data=latent_model), col="orange")
# abline(rq(dutchpay_request_num~recv_user_response_rate, tau=0.3, data=latent_model), col="yellow")
# #abline(rq(dutchpay_request_num~recv_user_response_rate, tau=0.4, data=latent_model), col="brown4")
# abline(rq(dutchpay_request_num~recv_user_response_rate, tau=0.5, data=latent_model), col="chocolate4")
# #abline(rq(dutchpay_request_num~recv_user_response_rate, tau=0.6, data=latent_model), col="coral4")
# abline(rq(dutchpay_request_num~recv_user_response_rate, tau=0.7, data=latent_model), col="cyan4")
# #abline(rq(dutchpay_request_num~recv_user_response_rate, tau=0.8, data=latent_model), col="darkgreen")
# abline(rq(dutchpay_request_num~recv_user_response_rate, tau=0.9, data=latent_model), col="black")
# 
# library(ggplot2)
# 
# ggplot(latent_model, aes(x=recv_user_response_rate, y=dutchpay_request_num)) + geom_point() + geom_quantile(quantiles = qs)

```

